### ISSUE TITLE
Unable to launch the simulation

### ISSUE THREAD

**Issue by botsbuzz** [WangChuan157/EnergyManagement#1]
Hi,

first of all thank you for your effort on this interesting project.

Unfortunately I'm not able to launch the simulation. 

`npm start`

returns the below log:

> > blockchain-dr-simulation@0.1.0 start /Users/stefano/Downloads/EnergyManagement
> > concurrently "node app.js" "python ./entities/simu_process.py"
> 
> [0] Launching NodeJS server with: 
> [0]  - 0 simulated Microgrid Manager
> [0]  - 1 simulated DER
> [0]  - 3 simulated Smart-Buildings
> [0] Publisher bound to port 3000
> [0] Subscriber connected to port 3001
> [0] (node:11894) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './data/output/planning_data.csv'
> [0] (node:11894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> [0] (node:11894) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> [1] Traceback (most recent call last):
> [1]   File "./entities/simu_process.py", line 10, in <module>
> [1]     from sg_entity_model import MicroGridManagerEntityModel, DistributedEnergyResourceEntityModel, SmartBuildingEntityModel
> [1]   File "/Users/stefano/Downloads/EnergyManagement/entities/sg_entity_model.py", line 610
> [1]     print generate_forecast(test_forecast, (8*3600, 24*3600, 900), test_fault)
> [1]                           ^
> [1] SyntaxError: invalid syntax
> [1] python ./entities/simu_process.py exited with code 1

Any idea on how to solve the issue?

Best,

Stefano

**Comment by yh-sh** [comment]
> Hi,
> 
> first of all thank you for your effort on this interesting project.
> 
> Unfortunately I'm not able to launch the simulation.
> 
> `npm start`
> 
> returns the below log:
> 
> > > blockchain-dr-simulation@0.1.0 start /Users/stefano/Downloads/EnergyManagement
> > > concurrently "node app.js" "python ./entities/simu_process.py"
> > 
> > 
> > [0] Launching NodeJS server with:
> > [0]  - 0 simulated Microgrid Manager
> > [0]  - 1 simulated DER
> > [0]  - 3 simulated Smart-Buildings
> > [0] Publisher bound to port 3000
> > [0] Subscriber connected to port 3001
> > [0] (node:11894) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './data/output/planning_data.csv'
> > [0] (node:11894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> > [0] (node:11894) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > [1] Traceback (most recent call last):
> > [1]   File "./entities/simu_process.py", line 10, in 
> > [1]     from sg_entity_model import MicroGridManagerEntityModel, DistributedEnergyResourceEntityModel, SmartBuildingEntityModel
> > [1]   File "/Users/stefano/Downloads/EnergyManagement/entities/sg_entity_model.py", line 610
> > [1]     print generate_forecast(test_forecast, (8_3600, 24_3600, 900), test_fault)
> > [1]                           ^
> > [1] SyntaxError: invalid syntax
> > [1] python ./entities/simu_process.py exited with code 1
> 
> Any idea on how to solve the issue?
> 
> Best,
> 
> Stefano

Hi,
Very glad to know that your are interested in this project.

I think your issue might be caused by this line:

> [0] (node:11894) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './data/output/planning_data.csv'``

But when I try to push the dir ./data to this repo, it tells me **'Everything up-to-date'**.

So, if you want get this data dir, just leave an email address, and I will sent it to you.

Best,
Zero
